say moving brick_block to main hand
replaceitem entity @s slot.weapon.mainhand 0 brick_block 1
execute if entity @s[hasitem={item=brick_block,quantity=1,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 air
execute if entity @s[hasitem={item=brick_block,quantity=2,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 1
execute if entity @s[hasitem={item=brick_block,quantity=3,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 2
execute if entity @s[hasitem={item=brick_block,quantity=4,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 3
execute if entity @s[hasitem={item=brick_block,quantity=5,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 4
execute if entity @s[hasitem={item=brick_block,quantity=6,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 5
execute if entity @s[hasitem={item=brick_block,quantity=7,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 6
execute if entity @s[hasitem={item=brick_block,quantity=8,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 7
execute if entity @s[hasitem={item=brick_block,quantity=9,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 8
execute if entity @s[hasitem={item=brick_block,quantity=10,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 9
execute if entity @s[hasitem={item=brick_block,quantity=11,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 10
execute if entity @s[hasitem={item=brick_block,quantity=12,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 11
execute if entity @s[hasitem={item=brick_block,quantity=13,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 12
execute if entity @s[hasitem={item=brick_block,quantity=14,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 13
execute if entity @s[hasitem={item=brick_block,quantity=15,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 14
execute if entity @s[hasitem={item=brick_block,quantity=16,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 15
execute if entity @s[hasitem={item=brick_block,quantity=17,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 16
execute if entity @s[hasitem={item=brick_block,quantity=18,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 17
execute if entity @s[hasitem={item=brick_block,quantity=19,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 18
execute if entity @s[hasitem={item=brick_block,quantity=20,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 19
execute if entity @s[hasitem={item=brick_block,quantity=21,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 20
execute if entity @s[hasitem={item=brick_block,quantity=22,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 21
execute if entity @s[hasitem={item=brick_block,quantity=23,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 22
execute if entity @s[hasitem={item=brick_block,quantity=24,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 23
execute if entity @s[hasitem={item=brick_block,quantity=25,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 24
execute if entity @s[hasitem={item=brick_block,quantity=26,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 25
execute if entity @s[hasitem={item=brick_block,quantity=27,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 26
execute if entity @s[hasitem={item=brick_block,quantity=28,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 27
execute if entity @s[hasitem={item=brick_block,quantity=29,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 28
execute if entity @s[hasitem={item=brick_block,quantity=30,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 29
execute if entity @s[hasitem={item=brick_block,quantity=31,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 30
execute if entity @s[hasitem={item=brick_block,quantity=32,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 31
execute if entity @s[hasitem={item=brick_block,quantity=33,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 32
execute if entity @s[hasitem={item=brick_block,quantity=34,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 33
execute if entity @s[hasitem={item=brick_block,quantity=35,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 34
execute if entity @s[hasitem={item=brick_block,quantity=36,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 35
execute if entity @s[hasitem={item=brick_block,quantity=37,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 36
execute if entity @s[hasitem={item=brick_block,quantity=38,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 37
execute if entity @s[hasitem={item=brick_block,quantity=39,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 38
execute if entity @s[hasitem={item=brick_block,quantity=40,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 39
execute if entity @s[hasitem={item=brick_block,quantity=41,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 40
execute if entity @s[hasitem={item=brick_block,quantity=42,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 41
execute if entity @s[hasitem={item=brick_block,quantity=43,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 42
execute if entity @s[hasitem={item=brick_block,quantity=44,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 43
execute if entity @s[hasitem={item=brick_block,quantity=45,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 44
execute if entity @s[hasitem={item=brick_block,quantity=46,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 45
execute if entity @s[hasitem={item=brick_block,quantity=47,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 46
execute if entity @s[hasitem={item=brick_block,quantity=48,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 47
execute if entity @s[hasitem={item=brick_block,quantity=49,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 48
execute if entity @s[hasitem={item=brick_block,quantity=50,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 49
execute if entity @s[hasitem={item=brick_block,quantity=51,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 50
execute if entity @s[hasitem={item=brick_block,quantity=52,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 51
execute if entity @s[hasitem={item=brick_block,quantity=53,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 52
execute if entity @s[hasitem={item=brick_block,quantity=54,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 53
execute if entity @s[hasitem={item=brick_block,quantity=55,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 54
execute if entity @s[hasitem={item=brick_block,quantity=56,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 55
execute if entity @s[hasitem={item=brick_block,quantity=57,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 56
execute if entity @s[hasitem={item=brick_block,quantity=58,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 57
execute if entity @s[hasitem={item=brick_block,quantity=59,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 58
execute if entity @s[hasitem={item=brick_block,quantity=60,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 59
execute if entity @s[hasitem={item=brick_block,quantity=61,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 60
execute if entity @s[hasitem={item=brick_block,quantity=62,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 61
execute if entity @s[hasitem={item=brick_block,quantity=63,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 62
execute if entity @s[hasitem={item=brick_block,quantity=64,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 brick_block 63