say moving planks to main hand
replaceitem entity @s slot.weapon.mainhand 0 planks 1
# Decrement the planks in the inventory - yes I know this is aweful
execute if entity @s[hasitem={item=planks,quantity=1,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 air
execute if entity @s[hasitem={item=planks,quantity=2,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 1
execute if entity @s[hasitem={item=planks,quantity=3,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 2
execute if entity @s[hasitem={item=planks,quantity=4,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 3
execute if entity @s[hasitem={item=planks,quantity=5,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 4
execute if entity @s[hasitem={item=planks,quantity=6,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 5
execute if entity @s[hasitem={item=planks,quantity=7,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 6
execute if entity @s[hasitem={item=planks,quantity=8,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 7
execute if entity @s[hasitem={item=planks,quantity=9,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 8
execute if entity @s[hasitem={item=planks,quantity=10,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 9
execute if entity @s[hasitem={item=planks,quantity=11,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 10
execute if entity @s[hasitem={item=planks,quantity=12,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 11
execute if entity @s[hasitem={item=planks,quantity=13,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 12
execute if entity @s[hasitem={item=planks,quantity=14,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 13
execute if entity @s[hasitem={item=planks,quantity=15,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 14
execute if entity @s[hasitem={item=planks,quantity=16,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 15
execute if entity @s[hasitem={item=planks,quantity=17,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 16
execute if entity @s[hasitem={item=planks,quantity=18,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 17
execute if entity @s[hasitem={item=planks,quantity=19,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 18
execute if entity @s[hasitem={item=planks,quantity=20,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 19
execute if entity @s[hasitem={item=planks,quantity=21,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 20
execute if entity @s[hasitem={item=planks,quantity=22,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 21
execute if entity @s[hasitem={item=planks,quantity=23,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 22
execute if entity @s[hasitem={item=planks,quantity=24,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 23
execute if entity @s[hasitem={item=planks,quantity=25,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 24
execute if entity @s[hasitem={item=planks,quantity=26,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 25
execute if entity @s[hasitem={item=planks,quantity=27,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 26
execute if entity @s[hasitem={item=planks,quantity=28,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 27
execute if entity @s[hasitem={item=planks,quantity=29,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 28
execute if entity @s[hasitem={item=planks,quantity=30,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 29
execute if entity @s[hasitem={item=planks,quantity=31,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 30
execute if entity @s[hasitem={item=planks,quantity=32,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 31
execute if entity @s[hasitem={item=planks,quantity=33,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 32
execute if entity @s[hasitem={item=planks,quantity=34,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 33
execute if entity @s[hasitem={item=planks,quantity=35,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 34
execute if entity @s[hasitem={item=planks,quantity=36,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 35
execute if entity @s[hasitem={item=planks,quantity=37,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 36
execute if entity @s[hasitem={item=planks,quantity=38,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 37
execute if entity @s[hasitem={item=planks,quantity=39,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 38
execute if entity @s[hasitem={item=planks,quantity=40,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 39
execute if entity @s[hasitem={item=planks,quantity=41,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 40
execute if entity @s[hasitem={item=planks,quantity=42,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 41
execute if entity @s[hasitem={item=planks,quantity=43,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 42
execute if entity @s[hasitem={item=planks,quantity=44,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 43
execute if entity @s[hasitem={item=planks,quantity=45,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 44
execute if entity @s[hasitem={item=planks,quantity=46,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 45
execute if entity @s[hasitem={item=planks,quantity=47,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 46
execute if entity @s[hasitem={item=planks,quantity=48,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 47
execute if entity @s[hasitem={item=planks,quantity=49,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 48
execute if entity @s[hasitem={item=planks,quantity=50,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 49
execute if entity @s[hasitem={item=planks,quantity=51,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 50
execute if entity @s[hasitem={item=planks,quantity=52,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 51
execute if entity @s[hasitem={item=planks,quantity=53,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 52
execute if entity @s[hasitem={item=planks,quantity=54,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 53
execute if entity @s[hasitem={item=planks,quantity=55,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 54
execute if entity @s[hasitem={item=planks,quantity=56,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 55
execute if entity @s[hasitem={item=planks,quantity=57,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 56
execute if entity @s[hasitem={item=planks,quantity=58,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 57
execute if entity @s[hasitem={item=planks,quantity=59,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 58
execute if entity @s[hasitem={item=planks,quantity=60,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 59
execute if entity @s[hasitem={item=planks,quantity=61,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 60
execute if entity @s[hasitem={item=planks,quantity=62,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 61
execute if entity @s[hasitem={item=planks,quantity=63,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 62
execute if entity @s[hasitem={item=planks,quantity=64,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 planks 63