say moving wool to main hand
replaceitem entity @s slot.weapon.mainhand 0 wool 1
# Decrement the wool in the inventory - yes I know this is aweful
execute if entity @s[hasitem={item=wool,quantity=1,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 air
execute if entity @s[hasitem={item=wool,quantity=2,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 1
execute if entity @s[hasitem={item=wool,quantity=3,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 2
execute if entity @s[hasitem={item=wool,quantity=4,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 3
execute if entity @s[hasitem={item=wool,quantity=5,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 4
execute if entity @s[hasitem={item=wool,quantity=6,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 5
execute if entity @s[hasitem={item=wool,quantity=7,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 6
execute if entity @s[hasitem={item=wool,quantity=8,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 7
execute if entity @s[hasitem={item=wool,quantity=9,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 8
execute if entity @s[hasitem={item=wool,quantity=10,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 9
execute if entity @s[hasitem={item=wool,quantity=11,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 10
execute if entity @s[hasitem={item=wool,quantity=12,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 11
execute if entity @s[hasitem={item=wool,quantity=13,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 12
execute if entity @s[hasitem={item=wool,quantity=14,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 13
execute if entity @s[hasitem={item=wool,quantity=15,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 14
execute if entity @s[hasitem={item=wool,quantity=16,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 15
execute if entity @s[hasitem={item=wool,quantity=17,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 16
execute if entity @s[hasitem={item=wool,quantity=18,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 17
execute if entity @s[hasitem={item=wool,quantity=19,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 18
execute if entity @s[hasitem={item=wool,quantity=20,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 19
execute if entity @s[hasitem={item=wool,quantity=21,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 20
execute if entity @s[hasitem={item=wool,quantity=22,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 21
execute if entity @s[hasitem={item=wool,quantity=23,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 22
execute if entity @s[hasitem={item=wool,quantity=24,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 23
execute if entity @s[hasitem={item=wool,quantity=25,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 24
execute if entity @s[hasitem={item=wool,quantity=26,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 25
execute if entity @s[hasitem={item=wool,quantity=27,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 26
execute if entity @s[hasitem={item=wool,quantity=28,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 27
execute if entity @s[hasitem={item=wool,quantity=29,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 28
execute if entity @s[hasitem={item=wool,quantity=30,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 29
execute if entity @s[hasitem={item=wool,quantity=31,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 30
execute if entity @s[hasitem={item=wool,quantity=32,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 31
execute if entity @s[hasitem={item=wool,quantity=33,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 32
execute if entity @s[hasitem={item=wool,quantity=34,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 33
execute if entity @s[hasitem={item=wool,quantity=35,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 34
execute if entity @s[hasitem={item=wool,quantity=36,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 35
execute if entity @s[hasitem={item=wool,quantity=37,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 36
execute if entity @s[hasitem={item=wool,quantity=38,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 37
execute if entity @s[hasitem={item=wool,quantity=39,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 38
execute if entity @s[hasitem={item=wool,quantity=40,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 39
execute if entity @s[hasitem={item=wool,quantity=41,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 40
execute if entity @s[hasitem={item=wool,quantity=42,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 41
execute if entity @s[hasitem={item=wool,quantity=43,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 42
execute if entity @s[hasitem={item=wool,quantity=44,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 43
execute if entity @s[hasitem={item=wool,quantity=45,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 44
execute if entity @s[hasitem={item=wool,quantity=46,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 45
execute if entity @s[hasitem={item=wool,quantity=47,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 46
execute if entity @s[hasitem={item=wool,quantity=48,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 47
execute if entity @s[hasitem={item=wool,quantity=49,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 48
execute if entity @s[hasitem={item=wool,quantity=50,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 49
execute if entity @s[hasitem={item=wool,quantity=51,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 50
execute if entity @s[hasitem={item=wool,quantity=52,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 51
execute if entity @s[hasitem={item=wool,quantity=53,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 52
execute if entity @s[hasitem={item=wool,quantity=54,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 53
execute if entity @s[hasitem={item=wool,quantity=55,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 54
execute if entity @s[hasitem={item=wool,quantity=56,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 55
execute if entity @s[hasitem={item=wool,quantity=57,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 56
execute if entity @s[hasitem={item=wool,quantity=58,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 57
execute if entity @s[hasitem={item=wool,quantity=59,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 58
execute if entity @s[hasitem={item=wool,quantity=60,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 59
execute if entity @s[hasitem={item=wool,quantity=61,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 60
execute if entity @s[hasitem={item=wool,quantity=62,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 61
execute if entity @s[hasitem={item=wool,quantity=63,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 62
execute if entity @s[hasitem={item=wool,quantity=64,location=slot.inventory,slot=0}] run replaceitem entity @s slot.inventory 0 wool 63